spring:
  datasource:
    url: jdbc:mysql://localhost/springboot-mybatis-mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
