spring:
  application:
    name: springboot-mybatis-mall
  profiles:
    active: dev
  mvc:
    view:
    # 页面默认前缀目录
      prefix: /WEB-INF/views/
       # 响应页面默认后缀
      suffix: .jsp
  freemarker:
      cache: false
      request-context-attribute: request
      checkTemplateLocation: false
  http:
    multipart:
      max-file-size: 200MB
      max-request-size: 2500MB
  datasource:
    url: jdbc:mysql://localhost/shopping?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
server:
  port: 8086
#日志级别
logging:
  level.com.shopping.mall: DEBUG
mybatis:
  mapperLocations: classpath*:mapper/*.xml
  type-aliases-package: com.shopping.mall
  configuration:
    mapUnderscoreToCamelCase: true
    use-generated-keys: true
    default-fetch-size: 100
    default-statement-timeout: 30
  check-config-location: true
mapper:
  mappers: com.shopping.mall.core.Mapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
management:
  security:
    enabled: false
