spring:
  application:
    name: springboot-mybatis-mall
  profiles:
    active: dev
  mvc:
    view:
    # 页面默认前缀目录
      prefix: /WEB-INF/views/
       # 响应页面默认后缀
      suffix: .jsp
  freemarker:
      cache: false
      request-context-attribute: request
      checkTemplateLocation: false
  http:
    multipart:
      max-file-size: 200MB
      max-request-size: 2500MB
  datasource:
    url: jdbc:mysql://localhost/shopping?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
#    # 下面为连接池的补充设置，应用到上面所有数据源中
    initialSize: 5
    minIdle: 5
    maxActive: 20
#    # 配置获取连接等待超时的时间
    maxWait: 60000
#    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
#    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
#    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    logSlowSql: true
server:
  port: 8086
logging:
  level.com.shopping.mall: DEBUG
mybatis:
  configuration.map-underscore-to-camel-case: true
  mapperLocations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.shopping.mall.domain
  configuration.use-generated-keys: true
  configuration.default-fetch-size: 100
  configuration.default-statement-timeout: 30
  check-config-location: true
  configuration:
    mapUnderscomvn clean compile test -DskipTests=falsereToCamelCase: true
mapper:
  mappers: com.shopping.mall.core.Mapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql